version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: paygo_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: paygo_db
      POSTGRES_USER: paygo_user
      POSTGRES_PASSWORD: paygo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./web-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - paygo_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: paygo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paygo_network

  # FastAPI Backend
  backend:
    build:
      context: ./web-service/backend
      dockerfile: Dockerfile
    container_name: paygo_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://paygo_user:paygo_password@database:5432/paygo_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    volumes:
      - ./web-service/backend:/app
    networks:
      - paygo_network

  # Frontend (Nginx)
  frontend:
    build:
      context: ./web-service/frontend
      dockerfile: Dockerfile
    container_name: paygo_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./web-service/frontend:/usr/share/nginx/html:ro
    networks:
      - paygo_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  paygo_network:
    driver: bridge





